### ISSUE TITLE
Logo for the project

### ISSUE THREAD

**Issue by rafaeelaudibert** [rafaeelaudibert/Encryptor#10]
A logo is needed for the project!

I'm open to ideas, although something related to a lock would fit pretty nicely IMO.

**Comment by AndChurchville** [comment]
Hi! I would like to try. I think a lock is a good idea so I'll design something around that. Do you have a certain color scheme in mind or I can just to black and white for right now.

**Comment by rafaeelaudibert** [comment]
> Hi! I would like to try. I think a lock is a good idea so I'll design something around that. Do you have a certain color scheme in mind or I can just to black and white for right now.

Sure!
I think a colorful one would be good as well, but I think something B&W would fit nicely!

**Comment by AndChurchville** [comment]
This is what I came up with! 
 ![encryptor-logo](https://user-images.githubusercontent.com/48935849/66341063-1acc8080-e90c-11e9-94a6-27872f917e0f.png)

**Comment by rafaeelaudibert** [comment]
Being worked at #24
