### ISSUE TITLE
Vigenere Cipher

### ISSUE THREAD

**Issue by rafaeelaudibert** [rafaeelaudibert/Encryptor#12]
Hello!

The [Vigenere Cipher](https://en.wikipedia.org/wiki/Vigen%C3%A8re_cipher) is available to be implemented!

Make sure to read our [contribution guidelines](https://github.com/rafaeelaudibert/Encryptor/blob/master/CONTRIBUTING.md)

**Comment by Artyko** [comment]
Hi, may I take up this one?

**Comment by rafaeelaudibert** [comment]
Being worked at #21
