### ISSUE TITLE
Blowfish

### ISSUE THREAD

**Issue by rafaeelaudibert** [rafaeelaudibert/Encryptor#14]
Hello!

The [Blowfish](https://en.wikipedia.org/wiki/Blowfish_(cipher)) is available to be implemented!

Make sure to read our [contribution guidelines](https://github.com/rafaeelaudibert/Encryptor/blob/master/CONTRIBUTING.md)

**Comment by mhrownaghi** [comment]
The Blowfish Algorithm implemented and is available in:
https://github.com/jashandeep-sohi/python-blowfish

**Comment by rafaeelaudibert** [comment]
> The Blowfish Algorithm implemented and is available in:
> https://github.com/jashandeep-sohi/python-blowfish

That looks like a great implementation! If you, or anybody else, wants to adapt it to match it to the API in this project, it would be awesome.
