### ISSUE TITLE
RSA

### ISSUE THREAD

**Issue by rafaeelaudibert** [rafaeelaudibert/Encryptor#19]
Hello!

The [RSA](https://en.wikipedia.org/wiki/RSA_(cryptosystem)) is available to be implemented!

Make sure to read our [contribution guidelines](https://github.com/rafaeelaudibert/Encryptor/blob/master/CONTRIBUTING.md)

**Comment by pragyanmehrotra** [comment]
Hey, I would like to take up this issue, I have a small doubt though like what is the input and output format of the encrypt and decrypt function meaning what all arguments do I need to provide to both the functions and what all should I return?

**Comment by rafaeelaudibert** [comment]
Hello @pragyanmehrotra, I'm happy you are interested in contributing to our project. Make sure to check our [contributing guidelines](https://github.com/rafaeelaudibert/Encryptor/blob/master/CONTRIBUTING.md) where there are examples explaining how you should build a new API endpoint. You can also check how the other Encryptor endpoints were made.

You basically will have to create an API endpoint, where you receive the text you want to encrypt in the base URL, and receive any extra parameter that the RSA encryption method requires. The encryption will be implemented in a separated class which MUST implement the Encrypt and Decrypt method, receiving the text to be en/decrypted and any extra parameters.

**Comment by rafaeelaudibert** [comment]
Closed as by #28
