### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by rafaeelaudibert** [rafaeelaudibert/Encryptor#29]
There are some (small) changes to some dependencies, which can be upgraded:
* Flask -> 1.1.2 
* Click -> 7.1.2
* Change Raven (deprecated) in favor of https://github.com/getsentry/sentry-python
* Pytest -> 6.1.1
* pytest-flask -> 1.0.0
* blowfish -> Pinnar na 0.6.1

**Comment by Anu9518** [comment]
I would like to take this up

**Comment by Anu9518** [comment]
The latest version of click is 7.1.2 not 7.2

**Comment by abhishekpatel946** [comment]
Hey @rafaeelaudibert 
I'll fix this dependency issue.

**Comment by rafaeelaudibert** [comment]
It is all yours @Anu9518! Thanks for the clarification, i fixed the issue description with the correct click version.

**Comment by Anu9518** [comment]
I have raised a PR, please do check.

**Comment by rafaeelaudibert** [comment]
Closed by #31
